/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.google.gson.Gson;

import model.adt.ApplianceADT;
import model.adt.UserADT;

import static org.junit.Assert.*;

import java.util.ArrayList;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test
    public void testGson() {
    	Gson gson = new Gson();
    	UserADT user = new UserADT("yoo", "yohelpme@help.com");
    	ArrayList<ApplianceADT> list = new ArrayList<ApplianceADT>();
    	list.add(new ApplianceADT("Woo", "LP6", "nice"));
    	user.setAppliances(list);
    	String json = gson.toJson(user);
    	System.out.println(json);
    	String lel = "woo";
    	System.out.println(lel.hashCode());
    	assert true;
    }
    
}
