package model.adt;

public class WasherADT extends ApplianceADT {
	
	private String MOD_J1_AEC, TYPE_LABEL_EN, TYPE_LABEL_FR, AVG_L_PER_CYCLE, PROD_CLASS_LABEL_EN, PROD_CLASS_LABEL_FR, PAYMENT_MECH_LABEL_EN, PAYMENT_MECH_LABEL_FR, CAPACITY, MAX_WASH_TEMP_AVAIL_LABEL_EN, MAX_WASH_TEMP_AVAIL_LABEL_FR, WATER_LEVELS_CONTROL_LABEL_EN, WATER_LEVELS_CONTROL_LABEL_FR, MOD_J1_EF_LIT, WATER_CON_FACTOR, ANNUAL_WATER_CON_L;
	
	public WasherADT(String BRAND_NAME, String MODEL_NUM_1, String REC_REF_KEY, String MOD_J1_AEC, String TYPE_LABEL_EN, String TYPE_LABEL_FR, String AVG_L_PER_CYCLE, String PROD_CLASS_LABEL_EN, String PROD_CLASS_LABEL_FR, String PAYMENT_MECH_LABEL_EN, String PAYMENT_MECH_LABEL_FR, String CAPACITY, String MAX_WASH_TEMP_AVAIL_LABEL_EN, String MAX_WASH_TEMP_AVAIL_LABEL_FR, String WATER_LEVELS_CONTROL_LABEL_EN, String WATER_LEVELS_CONTROL_LABEL_FR, String MOD_J1_EF_LIT, String WATER_CON_FACTOR, String ANNUAL_WATER_CON_L) {
		super(BRAND_NAME, MODEL_NUM_1, REC_REF_KEY);
		this.MOD_J1_AEC = MOD_J1_AEC;
		this.TYPE_LABEL_EN = TYPE_LABEL_EN; 
		this.TYPE_LABEL_FR = TYPE_LABEL_FR;
		this.AVG_L_PER_CYCLE = AVG_L_PER_CYCLE;
		this.PROD_CLASS_LABEL_EN = PROD_CLASS_LABEL_EN;
		this.PROD_CLASS_LABEL_FR = PROD_CLASS_LABEL_FR;
		this.PAYMENT_MECH_LABEL_EN = PAYMENT_MECH_LABEL_EN;
		this.PAYMENT_MECH_LABEL_FR = PAYMENT_MECH_LABEL_FR;
		this.CAPACITY = CAPACITY;
		this.MAX_WASH_TEMP_AVAIL_LABEL_EN = MAX_WASH_TEMP_AVAIL_LABEL_EN; 
		this.MAX_WASH_TEMP_AVAIL_LABEL_FR = MAX_WASH_TEMP_AVAIL_LABEL_FR;
		this.WATER_LEVELS_CONTROL_LABEL_EN = WATER_LEVELS_CONTROL_LABEL_EN;
		this.WATER_LEVELS_CONTROL_LABEL_FR = WATER_LEVELS_CONTROL_LABEL_FR; 
		this.MOD_J1_EF_LIT = MOD_J1_EF_LIT;
		this.WATER_CON_FACTOR = WATER_CON_FACTOR;
		this.ANNUAL_WATER_CON_L = ANNUAL_WATER_CON_L;
		
	}
	
	public String getMOD_J1_AEC() {
		return this.MOD_J1_AEC;
	}
	
	public String getTYPE_LABEL_EN() {
		return this.TYPE_LABEL_EN;
	}
	
	public String getTYPE_LABEL_FR() {
		return this.TYPE_LABEL_FR;
	}
	
	public String getAVG_L_PER_CYCLE() {
		return this.AVG_L_PER_CYCLE;
	}
	
	public String getPROD_CLASS_LABEL_EN() {
		return this.PROD_CLASS_LABEL_EN;
	}
	
	public String getPROD_CLASS_LABEL_FR() {
		return this.PROD_CLASS_LABEL_FR;
	}
	
	public String getPAYMENT_MECH_LABEL_EN() {
		return this.PAYMENT_MECH_LABEL_EN;
	}
	
	public String getPAYMENT_MECH_LABEL_FR() {
		return this.PAYMENT_MECH_LABEL_FR;
	}
	
	public String getCAPACITY() {
		return this.CAPACITY;
	}
	
	public String getMAX_WASH_TEMP_AVAIL_LABEL_EN() {
		return this.MAX_WASH_TEMP_AVAIL_LABEL_EN;
	}
	
	public String getMAX_WASH_TEMP_AVAIL_LABEL_FR() {
		return this.MAX_WASH_TEMP_AVAIL_LABEL_FR;
	}
	
	public String getWATER_LEVELS_CONTROL_LABEL_EN() {
		return this.WATER_LEVELS_CONTROL_LABEL_EN;
	}
	
	public String getWATER_LEVELS_CONTROL_LABEL_FR() {
		return this.WATER_LEVELS_CONTROL_LABEL_FR;
	}
	
	public String getMOD_J1_EF_LIT() {
		return this.MOD_J1_EF_LIT;
	}
	
	public String getWATER_CON_FACTOR() {
		return this.WATER_CON_FACTOR;
	}
	
	public String getANNUAL_WATER_CON_L() {
		return this.ANNUAL_WATER_CON_L;
	}
	
	
	

}